### PR TITLE
upgrade sbt, crossbuild for scala 2.11-13

### PR DESCRIPTION
**Pull request by oker1**
Please publish the new artifacts too!

### CODE REVIEW

**Comment by ps0uth** [comment]
Thanks @oker1 , I Haven't done much scala in the last year. Would you be interested in taking this project over?

**Comment by oker1** [comment]
Sure, I'd be happy to take over.

**Comment by oker1** [comment]
Should I take a project and publish under a new organization or you'd like to hand over the current publishing?

**Comment by oker1** [comment]
@philipsoutham ping

**Pull request merged**
